### ISSUE TITLE
build for vsomip folder giving errors

### ISSUE THREAD

**Issue by mohitrao12** [MicrochipTech/some-ip#2]
/MicrochipTech-some-ip/vsomeip/build$ make 
Consolidate compiler-generated dependencies of target vsomeip
[  1%] Building CXX object CMakeFiles/vsomeip.dir/implementation/endpoints/src/endpoint_impl.cpp.o
In the file included from /home/mytsp01872/MicrochipTech-some-ip/vsomeip/implementation/helper/boost/asio/basic_datagram_socket_ext.hpp:25,
                 from /home/mytsp01872/MicrochipTech-some-ip/vsomeip/implementation/helper/boost/asio/ip/udp_ext.hpp:20,
                 from /home/mytsp01872/MicrochipTech-some-ip/vsomeip/implementation/endpoints/src/endpoint_impl.cpp:8:
/home/mytsp01872/MicrochipTech-some-ip/vsomeip/implementation/helper/boost/asio/detail/handler_type_requirements_ext.hpp:54:11: fatal error: boost/asio/handler_type.hpp: No such file or directory
   54 | # include <boost/asio/handler_type.hpp>
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/vsomeip.dir/build.make:118: CMakeFiles/vsomeip.dir/implementation/endpoints/src/endpoint_impl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:149: CMakeFiles/vsomeip.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

Like this, there are lots of files which is not there this code is full of errors

capicxx-core-runtime  only this folder is build completely

**Comment by DearJim112** [comment]
didyou sovle this issue?

**Comment by tkummermehr** [comment]
Duplicated issue.
This is a common configuration issue. Not related to this project.
https://stackoverflow.com/questions/55306598/how-to-fix-fatal-error-boost-asio-hpp-no-such-file-or-directory
