### ISSUE TITLE
boost/asio/detail/addressof.hpp: No such file or directory

### ISSUE THREAD

**Issue by DearJim112** [MicrochipTech/some-ip#3]
gitpod /workspace/some-ip/vsomeip/build (master) $ sudo apt-get install doxygen asciidoc graphviz source-highlight libboost-system-dev libboost-thread-dev libboost-log-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libboost-system-dev is already the newest version (1.74.0.3ubuntu7).
libboost-thread-dev is already the newest version (1.74.0.3ubuntu7).
asciidoc is already the newest version (10.1.2-1).
doxygen is already the newest version (1.9.1-2ubuntu2).
graphviz is already the newest version (2.42.2-6).
libboost-log-dev is already the newest version (1.74.0.3ubuntu7).
source-highlight is already the newest version (3.1.9-4.1build2).
0 upgraded, 0 newly installed, 0 to remove and 64 not upgraded.
gitpod /workspace/some-ip/vsomeip/build (master) $ make clean
gitpod /workspace/some-ip/vsomeip/build (master) $ make
[  1%] Building CXX object CMakeFiles/vsomeip.dir/implementation/endpoints/src/client_endpoint_impl.cpp.o
[  2%] Building CXX object CMakeFiles/vsomeip.dir/implementation/endpoints/src/credentials.cpp.o
[  4%] Building CXX object CMakeFiles/vsomeip.dir/implementation/endpoints/src/endpoint_definition.cpp.o
[  5%] Building CXX object CMakeFiles/vsomeip.dir/implementation/endpoints/src/endpoint_impl.cpp.o
In file included from /workspace/some-ip/vsomeip/implementation/helper/boost/asio/datagram_socket_service_ext.hpp:33,
                 from /workspace/some-ip/vsomeip/implementation/helper/boost/asio/basic_datagram_socket_ext.hpp:24,
                 from /workspace/some-ip/vsomeip/implementation/helper/boost/asio/ip/udp_ext.hpp:20,
                 from /workspace/some-ip/vsomeip/implementation/endpoints/src/endpoint_impl.cpp:8:
/workspace/some-ip/vsomeip/implementation/helper/boost/asio/detail/reactive_socket_service_ext.hpp:29:10: fatal error: boost/asio/detail/addressof.hpp: No such file or directory
   29 | #include <boost/asio/detail/addressof.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/vsomeip.dir/build.make:118: CMakeFiles/vsomeip.dir/implementation/endpoints/src/endpoint_impl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:149: CMakeFiles/vsomeip.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by tkummermehr** [comment]
My first impression is that boost library is not installed or the path to the include directory of the boost library is not correct set.

**Comment by Nitind7** [comment]
> gitpod /workspace/some-ip/vsomeip/build (master) $ sudo apt-get install doxygen asciidoc graphviz source-highlight libboost-system-dev libboost-thread-dev libboost-log-dev Reading package lists... Done Building dependency tree... Done Reading state information... Done libboost-system-dev is already the newest version (1.74.0.3ubuntu7). libboost-thread-dev is already the newest version (1.74.0.3ubuntu7). asciidoc is already the newest version (10.1.2-1). doxygen is already the newest version (1.9.1-2ubuntu2). graphviz is already the newest version (2.42.2-6). libboost-log-dev is already the newest version (1.74.0.3ubuntu7). source-highlight is already the newest version (3.1.9-4.1build2). 0 upgraded, 0 newly installed, 0 to remove and 64 not upgraded. gitpod /workspace/some-ip/vsomeip/build (master) $ make clean gitpod /workspace/some-ip/vsomeip/build (master) $ make [ 1%] Building CXX object CMakeFiles/vsomeip.dir/implementation/endpoints/src/client_endpoint_impl.cpp.o [ 2%] Building CXX object CMakeFiles/vsomeip.dir/implementation/endpoints/src/credentials.cpp.o [ 4%] Building CXX object CMakeFiles/vsomeip.dir/implementation/endpoints/src/endpoint_definition.cpp.o [ 5%] Building CXX object CMakeFiles/vsomeip.dir/implementation/endpoints/src/endpoint_impl.cpp.o In file included from /workspace/some-ip/vsomeip/implementation/helper/boost/asio/datagram_socket_service_ext.hpp:33, from /workspace/some-ip/vsomeip/implementation/helper/boost/asio/basic_datagram_socket_ext.hpp:24, from /workspace/some-ip/vsomeip/implementation/helper/boost/asio/ip/udp_ext.hpp:20, from /workspace/some-ip/vsomeip/implementation/endpoints/src/endpoint_impl.cpp:8: /workspace/some-ip/vsomeip/implementation/helper/boost/asio/detail/reactive_socket_service_ext.hpp:29:10: fatal error: boost/asio/detail/addressof.hpp: No such file or directory 29 | #include <boost/asio/detail/addressof.hpp> | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. make[2]: *** [CMakeFiles/vsomeip.dir/build.make:118: CMakeFiles/vsomeip.dir/implementation/endpoints/src/endpoint_impl.cpp.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:149: CMakeFiles/vsomeip.dir/all] Error 2 make: *** [Makefile:136: all] Error 2

Did you solve this issue? :-)

**Comment by tkummermehr** [comment]
Just did a quick google search, this is a common issue.

One of the results:
https://stackoverflow.com/questions/55306598/how-to-fix-fatal-error-boost-asio-hpp-no-such-file-or-directory

**Comment by tkummermehr** [comment]
This is a common issue, not related to this project.
